### PR TITLE
Documentation JWT

### PR DESCRIPTION
**Pull request by Jaxom99**
## Problem

- le JWT bloque certaines installations/mises à jour.

## Solution

- *Documentation dans le Readme FR et EN

## PR Status

- [ N/A ] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by biva** [comment]
Thanks! May I suggest including this paragraph in the "Configuration of ONLYOFFICE Server" section, instead of "How to edit ONLYOFFICE documents?"

**Comment by Jaxom99** [comment]
Hum, yeah, I did not read the whole readme first :sweat_smile:  I will do commits in the week, or you can do it...

**Comment by Jaxom99** [comment]
done :nerd_face:

**Comment by ericgaspar** [comment]
closing with  #113

**Pull request closed without merging**
