### PR TITLE
Fix gpg

### PR DESCRIPTION
**Pull request by rodinux**
## Problem

- *try fix gpg repo not using apt-key signing*
- *new systemd services, supervisord is changed for ds-* services*

## Solution

- *edit how get a repo for onlyoffice like explain on the documentation*
- *reload the `ds-*` services*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
!testme

**Comment by rodinux** [comment]
Last try, does linter absolutely need an upgrade from old commit ?
!testme

**Comment by rodinux** [comment]
since it is late and nobody seems use the CLI, a last test to be sure...
!testme

**Comment by Salamandar** [comment]
Changes were merged to master, thanks <3

**Pull request closed without merging**
