### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Gredin67** [comment]
Install successes (after a previous remove, see #87 
But I get
```
Warning: ds:docservice: ERROR (no such process)
Warning: ds:docservice: ERROR (no such process)
Warning: ds:converter: ERROR (no such process)
Warning: ds:converter: ERROR (no such process)
```

**Comment by Gredin67** [comment]
@zamentur could you review this PR?

**Comment by Gredin67** [comment]
> But I get
> 
> ```
> Warning: ds:docservice: ERROR (no such process)
> Warning: ds:docservice: ERROR (no such process)
> Warning: ds:converter: ERROR (no such process)
> Warning: ds:converter: ERROR (no such process)
> ```

This can be manually solved by #84 and #88 or automatically with https://github.com/YunoHost-Apps/nextcloud_ynh/issues/537

**Comment by Gredin67** [comment]
@ericgaspar I incidentally pushed to the Testing branch some changes in the README. https://github.com/YunoHost-Apps/onlyoffice_ynh/pull/86/commits/b2b18e129fe290543282aeeb8dd88f92aaf63686
And I realized that the auto-updater erased it. How can I get the changes merged?

**Comment by ericgaspar** [comment]
@Gredin67 The `README.md` and `README_fr.md` files are generated automatically from the `DESCRIPTION.md`, `DISCLAIMER.md`, `DESCRIPTION_fr.md` and `DISCLAIMER_fr.md`  files. If you want to modify something in the README, you must modify these files.

**Comment by ericgaspar** [comment]
!testme

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
!testme

**Comment by Gredin67** [comment]
@ericgaspar @zamentur CI seems to be happy, except for some warnings.
What about you, something more to add? Should we solve the issue with the JWT Token for direct integration between onlyoffice_ynh and nextcloud_ynh https://github.com/YunoHost-Apps/nextcloud_ynh/issues/537 and #88 
```
 649500 WARNING Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
650054 WARNING gpg: key 8320CA65CB2DE8E5: public key "Ascensio System Limited (ONLYOFFICE) <support@onlyoffice.com>" imported
650070 WARNING gpg: Total number processed: 1
650071 WARNING gpg:               imported: 1
1088832 WARNING adduser: Warning: The home directory `/var/www/onlyoffice/documentserver' does not belong to the user you are currently creating.
1089008 WARNING Adding user www-data to group ds
1097520 WARNING ds:docservice: ERROR (no such process)
1097520 WARNING ds:docservice: ERROR (no such process)
1098080 WARNING ds:converter: ERROR (no such process)
1098080 WARNING ds:converter: ERROR (no such process)
1103932 WARNING Generating AllFonts.js, please wait...Done
1146913 WARNING Generating presentation themes, please wait...Done
1150768 WARNING Generating js caches, please wait...Done
1151527 WARNING Congratulations, the ONLYOFFICE documentserver has been installed successfully!
1151528 WARNING JWT is enabled by default. A random secret is generated automatically. Run the command '# documentserver-jwt-status.sh' to get information about JWT.
```

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
