### PR TITLE
Fix install

### PR DESCRIPTION
**Pull request by sebmennetrier**
## Problem

- Installation failed

## Solution

- Use GPG key provided by official documentation of installation
- Don't use supervisorctl anymore. Starting version 7.3.0 supervisorctl is replaced by use of systemd (https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#730) `Service manager in the onlyoffice-documentserver packages changed from supervisord to systemd to get rid of excess dependence and simplify functionality for end users`

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by sebmennetrier** [comment]
!testme

**Comment by sebmennetrier** [comment]
!gogogadgetoci

**Comment by sebmennetrier** [comment]
By the power of systemd, I invoke The Great App CI to test this Pull Request!

**Comment by sebmennetrier** [comment]
The test that failed seems trying install the last onlyoffice (that working with systemd) with the old version of recipe (that is configured with supervisorctl). I suggest to remove this test that can't working.

**Comment by rodinux** [comment]
Hello, you are on the right way to debug :+1: 

Can you try this, just put the same lines found in the install for the upgrade script, and remove the old one

```
apt-key del CB2DE8E5

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5 2>/dev/null

ynh_install_extra_app_dependencies --repo="https://download.onlyoffice.com/repo/debian squeeze main" --package=$extra_dependencies --key="https://download.onlyoffice.com/GPG-KEY-ONLYOFFICE"
```

**Comment by rodinux** [comment]
You help me a lot, thanks. I have try a PR also before seen your code, now I am testing it...

**Comment by sebmennetrier** [comment]
!testme

**Comment by sebmennetrier** [comment]
Thanks @rodinux, I forgot to modify upgrade script. It's done now.

**Comment by ericgaspar** [comment]
I am unable to test this PR now. Is it tested, is it mergable in tesing?

**Comment by sebmennetrier** [comment]
I used it today on several servers and it's working. I think it should be OK :crossed_fingers:

**Comment by rodinux** [comment]
Ok, for me the upgrade fails with an error when trying connect Nextcloud Onlyoffice. Something like 
` Server error: `GET https://onlyoffice.linux07.fr/healthcheck` resulted in a `502 Bad Gateway` ngin (truncated...)`
I Finally remove Onlyoffice_ynh and reisntall it. 

Also to use Onlyoffice connector on Nextcloud, I had to add the secret key whis is found in the file ` /etc/onlyoffice/documentserver/local.json` to make works onlyoffice. On another server it was similar...

**Pull request merged**
