### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by Gredin67**
## Problem

- *Level 0*

## Solution

- *Fix install*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by zamentur** [comment]
!testme

**Comment by zamentur** [comment]
TODO:
- [ ] Fix [#75](https://github.com/YunoHost-Apps/onlyoffice_ynh/issues/75)
- [ ] Fix permission issues
- [ ] Fix configuration upgrade

**Comment by ericgaspar** [comment]
!testme

**Comment by Gredin67** [comment]
I installed this and the bug with nextcloud is not there anymore.

**Review by ericgaspar — APPROVED** [review]

**Comment by zamentur** [comment]
NB: the upgrade doesn't work cause the onlyoffice format totally change.

**Comment by ericgaspar** [comment]
!testme

**Comment by zamentur** [comment]
ttf-mscorefonts-installer is now required by onlyoffice, so contrib repo should be enabled.

**Comment by ericgaspar** [comment]
I just thought i would add `ttf-mscorefonts-installer` to `extra_dependencies` do we need to do something else?

**Comment by zamentur** [comment]
Yes cause this package is in contrib debian repo, not just in main component. So i had to update /etc/apt/sources.list

In more i had to extract the default.json cause it's not updated by our helpers:
```
dpkg-deb --fsys-tarfile /var/cache/apt/archives/onlyoffice-documentserver_7.1.0-215_amd64.deb | tar -x ./etc/onlyoffice/documentserver/default.json
```

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
@zamentur : do you think it's ok to merge ?

**Pull request merged**
