### PR TITLE
Send the jwt token via email to the admin

### PR DESCRIPTION
**Pull request by Typhlos**
## Problem

- Since OnlyOffice 7.2, OnlyOffice requires a JWT token to be able to connect an external app to it such as Nextcloud. Cf issue #84 

## Solution

- Send the JWT token via email to an admin specified when installing the app

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Typhlos** [comment]
For the warning in the linting, it is due to the fact that I use a function that is still not in the official helpers of yunohost but that is supposed to be there in the future : https://github.com/YunoHost-Apps/Experimental_helpers/blob/aa8bd81538dccf46c98fef7eef3f7a4ed2be75ee/ynh_send_readme_to_admin/ynh_send_readme_to_admin__2

As for the failure on upgrade (eca1121f), it seems due to the `apt upgrade` failing. As I haven't changed the upgrade code, I'm not sure if it is due to my changes and if I can do much to fix that.

**Comment by Typhlos** [comment]
Hello,

Just wanted to know if there is any update or feedback on my PR. If there is something to change, I'll happily look into it.

**Comment by Gredin67** [comment]
Other options to solve #84 from nextcloud_ynh
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/537

**Comment by Gredin67** [comment]
if we go for this option, we should adapt the README

**Comment by Typhlos** [comment]
Indeed, I did not think about updating the README, I'll add an explanation

**Pull request merged**
